language: cpp
compiler: clang
before_install:
  - ./travis-ci/travis_install_packages.sh
  - ./travis-ci/travis_build_ninja.sh
  - ./travis-ci/travis_build_libcxx.sh
  - ./travis-ci/travis_build_boost.sh
script: ./scripts/travis_build.sh
notifications:
  email: false
